<?php

/* SETTINGS START */

$themeSettings = array(
'bar_background' => '#F38918',
'bar_gradient_start' => '#F38918',
'bar_gradient_end' => '#F38918',
'bar_border' => '#F38918',
'bar_color' => '#FFFFF',
'bar_color_disabled' => '#A7A7A7',
'bar_border_light' => '#E5E5E5',
'bar_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'bar_font_size' => '11px',
'bar_text_background' => '#FFFFFF',
'tab_background' => '#FFFFFF',
'tab_color' => '#111111',
'tab_border' => '#FFFFFF',
'tab_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'tab_font_size' => '11px',
'tab_font_size_small' => '10px',
'tab_color_self' => '#F38918',
'tab_title_color' => '#FFFFFF',
'tab_title_backgroud_light' => '#F38918',
'tab_title_background' => '#F38918',
'tab_title_gradient_start' => '#F38918',
'tab_title_gradient_end' => '#F38918',
'tab_title_border' => '#FFFFFF',
'tab_title_font_family' => 'Tahoma,Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'tab_title_font_size' => '11px',
'tab_title_font_size_large' => '12px',
'tab_title_text_background' => '#F38918',
'tab_sub_background' => '#EEEEEE',
'tab_sub_color' => '#666666',
'tab_border_light' => '#CCCCCC',
'tab_border_lighter' => '#EEEEEE',
'tooltip_background' => '#F38918',
'tooltip_color' => '#FFFFFF',
'tooltip_color_light' => '#EEEEEE',
'tooltip_font_family' => '"Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif',
'tooltip_font_size' => '11px',
'tooltip_break' => '#666666',
'tab_link_color' => '#288597',
);

/* SETTINGS END */
